[[annotation]]
file='/home/mcgaugheyd/bin/eye_genes_disease.bed.gz'
columns=[4]
names=['Gene_EyeDiseaseClass']
ops=['concat']

[[annotation]]
file='/home/mcgaugheyd/bin/exac.scores.bed.gz'
columns=[5,6,7,8,9,10,11,12,13,14,15,16]
names=['n_syn','adj_exp_syn','syn_z','n_mis','adj_exp_mis','mis_z','n_lof','adj_exp_lof','lof_z','pLI','pRecessive','pNull']
ops=['concat','concat','concat','concat','concat','concat','concat','concat','concat','concat','concat','concat']

